---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tools
  namespace: cncp-system
data:
  entrypoint.sh: |-
    #!/usr/bin/env sh
    set -e -u
    /usr/sbin/sshd
    tail -f /dev/null

---
kind: Service
apiVersion: v1
metadata:
  name: tools
  namespace: cncp-system
spec:
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 32022
  selector:
    cncp-component: tools
  type: NodePort

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tools
  namespace: cncp-system
spec:
  replicas: 1
  selector:
    matchLabels:
      cncp-component: tools
  template:
    metadata:
      labels:
        cncp-component: tools
    spec:
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          name: tools
          defaultMode: 511
      - name: pki
        hostPath:
          path: /system/secrets
          type: DirectoryOrCreate
      containers:
      - name: tools
        #image: mingyangtech.com.cn/mingyang/tools:v1.1.0
        image: mingyangtech.com.cn/mingyang/tools:v1.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
          limits:
            cpu: 1000m
            memory: 4Gi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: config
          mountPath: /usr/local/bin/entrypoint.sh
          subPath: entrypoint.sh
        - name: pki
          mountPath: /system/secrets
        securityContext:
          privileged: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
  strategy:
    type: Recreate
